apiVersion: v1
kind: Secret
metadata:
  name: pi-hw-monitor
  namespace: monitoring
type: Opaque
data:
  # REPLACE ALL THESE VALUES eg using echo -n "production" | base64 
  ENV: cHJvZHVjdGlvbg==         # base64-encoded value for "production"
  SAMPLE_INTERVAL: NzAw          # base64-encoded value for "700"
  INFLUX_URL: aHR0cDovL2xvY2FsaG9zdDo4MDg2    # base64-encoded value for "http://localhost:8086"
  INFLUX_TOKEN: AAAA
  INFLUX_BUCKET: bXktaW5mbHV4LWJ1Y2tldA==   # base64-encoded value for "my-influx-bucket"
  INFLUX_ORG: bXktaW5mbHV4LW9yZw==          # base64-encoded value for "my-influx-org"