# simple python pod to be able to exec into
apiVersion: v1
kind: Pod
metadata:
  name: python-container
spec:
  containers:
  - name: python-container
    image: bengan/pi-hardware-monitor:0.3-slim
    command: ["/bin/bash", "-c", "sleep 3600"]
    # args: ["print('Hello, Kubernetes!')"]